export { default as Landing } from './Landing/Landing'
export { default as Aboutus } from './Aboutus/Aboutus'
export { default as ProjectDetails } from './ProjectDetails'
export { default as Donate } from './Donate/Donate'
export { default as Shop } from './Shop/Shop'
export { default as BecomeVolunteerForm } from './BecomeVolunteerForm/BecomeVolunteerForm'
