/* eslint-disable max-len */
import { lazy } from 'react'

export const Navbar = lazy(() => import('./Navbar/Navbar' /* webpackChunkName: "Navbar" */))
export const AboutUs = lazy(() => import('./Aboutus/Aboutus' /* webpackChunkName: "AboutUs section" */))
export const Events = lazy(() => import('./Events/Events' /* webpackChunkName: "Events_section" */))
export const Hero = lazy(() => import('./Hero/Hero' /* webpackChunkName: "Hero" */))
export const LogosCarousel = lazy(() => import('./LogosCarousel/LogosCarousel' /* webpackChunkName: "LogosCarousel" */))
export const PremiumEvent = lazy(() => import('./PremiumEvent/PremiumEvent' /* webpackChunkName: "PremiumEventSection" */))
export const Projects = lazy(() => import('./Projects/Projects' /* webpackChunkName: "Projects_section" */))
export const SocialImpact = lazy(() => import('./SocialImpact/SocialImpact' /* webpackChunkName: "SocialImpact_section" */))
export const SubscribeDivider = lazy(() => import('./SubscribeDivider/SubscribeDivider' /* webpackChunkName: "SubscribeDivider" */))
export const Footer = lazy(() => import('./Footer/Footer' /* webpackChunkName: "Footer" */))
export const Volunteers = lazy(() => import('./Volunteers/Volunteers' /* webpackChunkName: "Volunteers section" */))
export const Divider = lazy(() => import('./Divider/Divider' /* webpackChunkName: "Divider" */))
export const Courses = lazy(() => import('./Courses/Courses' /* webpackChunkName: "Courses_section" */))
export const DonateForm = lazy(() => import('./Forms/DonateForm' /* webpackChunkName: "DonateForm" */))
export const BuyModal = lazy(() => import('./BuyModal' /* webpackChunkName: "BuyModal" */))
export const FinalizePaymentResult = lazy(() => import('./FinalizePaymentResult' /* webpackChunkName: "FinalizePaymentResult" */))
export const Map = lazy(() => import('./Map' /* webpackChunkName: "Map" */))
export const LoadingIndex = lazy(() => import('./LoadingIndex/LoadingIndex' /* webpackChunkName: "LoadingIndex" */))
